### ISSUE TITLE
Question: can relaton "auto-fetch" a citation using a DOI?

### ISSUE THREAD

**Issue by ReesePlews** [relaton/relaton.org#41]
hello, just a question about whether or not relaton "auto-fetch" a citation using a DOI? i recall an informal discussion, possibly with Ron, about this, and i looked but could not find the status. 

i would like to use "auto-fetch" with a DOI when authoring using metanorma to create bibliographic entries. 

would something like this be possible in the future?  thank you.

**Comment by ReesePlews** [comment]
hello @opoudjis do you know if my question is slated for implementation, and if so approximately when? thank you

**Comment by opoudjis** [comment]
@ReesePlews , I'm really sorry, but I simply cannot keep up to date with notifications, and check them only once every couple of months.

The answer is, this was indeed implemented, in December 2022. To do a DOI autofetch, do the following in the Asciidoctor:

````
* [[[ref1,doi:10.1515/9783110889406.257]]] _Standard_
````

That will fetch the DOI record for 10.1515/9783110889406.257 , and parse as much of it as CrossRef has marked up intelligibly into Relaton.

This was documented in https://github.com/metanorma/metanorma.org/pull/694 . Unfortunately the last seven months of updates to metanorma.org have not been reviewed nor released.
