### ISSUE TITLE
Add page for PLATEAU documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton.org#66]
Please help update relaton.org to show how to cite PLATEAU documents. Thanks.

_Originally posted by @ronaldtse in https://github.com/relaton/relaton-plateau/issues/3#issuecomment-2249458295_

**Comment by andrew2net** [comment]
Added

**Comment by ronaldtse** [comment]
@andrew2net thanks. Next time can you make a PR and then in the commit write “fixes #N” then when the PR merges it automatically closes? Thanks.
